await page.to("http://vsp.jd.com")
await page.changeIframe("loginChildPage")
await dom.click("[placeholder=\"请输入用户名\"]")
await dom.fill("[placeholder=\"请输入用户名\"]","2222")
await dom.click("[placeholder=\"密码\"]")
await dom.fill("[placeholder=\"密码\"]","33333")
await page.changeIframe(-1)
await dom.click("div:nth-child(2) .item_img img")
