await page.to("https://baidu.com")
await dom.click("input[name=\"wd\"]")
await dom.fill("input[name=\"wd\"]","666")
await img.click("/Users/zhouyuan11/work/cherry/core/tests/baidu_btn.jpg")
await sleep(3000)